// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.0
// source: Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender        uint32                 `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_Message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Chamael-2pHotstuff使用的消息类型
type New_View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	None          []byte                 `protobuf:"bytes,1,opt,name=none,proto3" json:"none,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *New_View) Reset() {
	*x = New_View{}
	mi := &file_Message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *New_View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*New_View) ProtoMessage() {}

func (x *New_View) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use New_View.ProtoReflect.Descriptor instead.
func (*New_View) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *New_View) GetNone() []byte {
	if x != nil {
		return x.None
	}
	return nil
}

type Prepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	mi := &file_Message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *Prepare) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type Prepare_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          uint32                 `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prepare_Vote) Reset() {
	*x = Prepare_Vote{}
	mi := &file_Message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prepare_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare_Vote) ProtoMessage() {}

func (x *Prepare_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare_Vote.ProtoReflect.Descriptor instead.
func (*Prepare_Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *Prepare_Vote) GetVote() uint32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *Prepare_Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Precommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggsig        []byte                 `protobuf:"bytes,1,opt,name=aggsig,proto3" json:"aggsig,omitempty"`
	Aggpk         []byte                 `protobuf:"bytes,2,opt,name=aggpk,proto3" json:"aggpk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Precommit) Reset() {
	*x = Precommit{}
	mi := &file_Message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Precommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Precommit) ProtoMessage() {}

func (x *Precommit) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Precommit.ProtoReflect.Descriptor instead.
func (*Precommit) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *Precommit) GetAggsig() []byte {
	if x != nil {
		return x.Aggsig
	}
	return nil
}

func (x *Precommit) GetAggpk() []byte {
	if x != nil {
		return x.Aggpk
	}
	return nil
}

type Precommit_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          uint32                 `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Precommit_Vote) Reset() {
	*x = Precommit_Vote{}
	mi := &file_Message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Precommit_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Precommit_Vote) ProtoMessage() {}

func (x *Precommit_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Precommit_Vote.ProtoReflect.Descriptor instead.
func (*Precommit_Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *Precommit_Vote) GetVote() uint32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *Precommit_Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggsig        []byte                 `protobuf:"bytes,1,opt,name=aggsig,proto3" json:"aggsig,omitempty"`
	Aggpk         []byte                 `protobuf:"bytes,2,opt,name=aggpk,proto3" json:"aggpk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_Message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{6}
}

func (x *Commit) GetAggsig() []byte {
	if x != nil {
		return x.Aggsig
	}
	return nil
}

func (x *Commit) GetAggpk() []byte {
	if x != nil {
		return x.Aggpk
	}
	return nil
}

var File_Message_proto protoreflect.FileDescriptor

const file_Message_proto_rawDesc = "" +
	"\n" +
	"\rMessage.proto\"Y\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\rR\x06sender\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x1e\n" +
	"\bNew_View\x12\x12\n" +
	"\x04none\x18\x01 \x01(\fR\x04none\"\x1b\n" +
	"\aPrepare\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"4\n" +
	"\fPrepare_Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\rR\x04vote\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"9\n" +
	"\tPrecommit\x12\x16\n" +
	"\x06aggsig\x18\x01 \x01(\fR\x06aggsig\x12\x14\n" +
	"\x05aggpk\x18\x02 \x01(\fR\x05aggpk\"6\n" +
	"\x0ePrecommit_Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\rR\x04vote\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"6\n" +
	"\x06Commit\x12\x16\n" +
	"\x06aggsig\x18\x01 \x01(\fR\x06aggsig\x12\x14\n" +
	"\x05aggpk\x18\x02 \x01(\fR\x05aggpkB\vZ\t/protobufb\x06proto3"

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData []byte
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP([]byte(file_Message_proto_rawDesc))
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Message_proto_goTypes = []any{
	(*Message)(nil),        // 0: Message
	(*New_View)(nil),       // 1: New_View
	(*Prepare)(nil),        // 2: Prepare
	(*Prepare_Vote)(nil),   // 3: Prepare_Vote
	(*Precommit)(nil),      // 4: Precommit
	(*Precommit_Vote)(nil), // 5: Precommit_Vote
	(*Commit)(nil),         // 6: Commit
}
var file_Message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: []byte(file_Message_proto_rawDesc),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
