// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.0
// source: Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender        uint32                 `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_Message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// HotStuff (2-phase) messages
type HS_New_View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	None          []byte                 `protobuf:"bytes,1,opt,name=none,proto3" json:"none,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_New_View) Reset() {
	*x = HS_New_View{}
	mi := &file_Message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_New_View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_New_View) ProtoMessage() {}

func (x *HS_New_View) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_New_View.ProtoReflect.Descriptor instead.
func (*HS_New_View) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *HS_New_View) GetNone() []byte {
	if x != nil {
		return x.None
	}
	return nil
}

type HS_Prepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Prepare) Reset() {
	*x = HS_Prepare{}
	mi := &file_Message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Prepare) ProtoMessage() {}

func (x *HS_Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Prepare.ProtoReflect.Descriptor instead.
func (*HS_Prepare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *HS_Prepare) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type HS_Prepare_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          uint32                 `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Prepare_Vote) Reset() {
	*x = HS_Prepare_Vote{}
	mi := &file_Message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Prepare_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Prepare_Vote) ProtoMessage() {}

func (x *HS_Prepare_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Prepare_Vote.ProtoReflect.Descriptor instead.
func (*HS_Prepare_Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *HS_Prepare_Vote) GetVote() uint32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *HS_Prepare_Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type HS_Precommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggsig        []byte                 `protobuf:"bytes,1,opt,name=aggsig,proto3" json:"aggsig,omitempty"`
	Aggpk         []byte                 `protobuf:"bytes,2,opt,name=aggpk,proto3" json:"aggpk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Precommit) Reset() {
	*x = HS_Precommit{}
	mi := &file_Message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Precommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Precommit) ProtoMessage() {}

func (x *HS_Precommit) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Precommit.ProtoReflect.Descriptor instead.
func (*HS_Precommit) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *HS_Precommit) GetAggsig() []byte {
	if x != nil {
		return x.Aggsig
	}
	return nil
}

func (x *HS_Precommit) GetAggpk() []byte {
	if x != nil {
		return x.Aggpk
	}
	return nil
}

type HS_Precommit_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          uint32                 `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Precommit_Vote) Reset() {
	*x = HS_Precommit_Vote{}
	mi := &file_Message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Precommit_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Precommit_Vote) ProtoMessage() {}

func (x *HS_Precommit_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Precommit_Vote.ProtoReflect.Descriptor instead.
func (*HS_Precommit_Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *HS_Precommit_Vote) GetVote() uint32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *HS_Precommit_Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type HS_Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggsig        []byte                 `protobuf:"bytes,1,opt,name=aggsig,proto3" json:"aggsig,omitempty"`
	Aggpk         []byte                 `protobuf:"bytes,2,opt,name=aggpk,proto3" json:"aggpk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Commit) Reset() {
	*x = HS_Commit{}
	mi := &file_Message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Commit) ProtoMessage() {}

func (x *HS_Commit) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Commit.ProtoReflect.Descriptor instead.
func (*HS_Commit) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{6}
}

func (x *HS_Commit) GetAggsig() []byte {
	if x != nil {
		return x.Aggsig
	}
	return nil
}

func (x *HS_Commit) GetAggpk() []byte {
	if x != nil {
		return x.Aggpk
	}
	return nil
}

// RBC messages
type RBC_Propose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Propose) Reset() {
	*x = RBC_Propose{}
	mi := &file_Message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Propose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Propose) ProtoMessage() {}

func (x *RBC_Propose) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Propose.ProtoReflect.Descriptor instead.
func (*RBC_Propose) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{7}
}

func (x *RBC_Propose) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type RBC_Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Echo) Reset() {
	*x = RBC_Echo{}
	mi := &file_Message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Echo) ProtoMessage() {}

func (x *RBC_Echo) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Echo.ProtoReflect.Descriptor instead.
func (*RBC_Echo) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{8}
}

func (x *RBC_Echo) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type RBC_Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	H             []byte                 `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Ready) Reset() {
	*x = RBC_Ready{}
	mi := &file_Message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Ready) ProtoMessage() {}

func (x *RBC_Ready) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Ready.ProtoReflect.Descriptor instead.
func (*RBC_Ready) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{9}
}

func (x *RBC_Ready) GetH() []byte {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *RBC_Ready) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_Message_proto protoreflect.FileDescriptor

const file_Message_proto_rawDesc = "" +
	"\n" +
	"\rMessage.proto\"Y\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\rR\x06sender\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"!\n" +
	"\vHS_New_View\x12\x12\n" +
	"\x04none\x18\x01 \x01(\fR\x04none\"\x1e\n" +
	"\n" +
	"HS_Prepare\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"7\n" +
	"\x0fHS_Prepare_Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\rR\x04vote\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"<\n" +
	"\fHS_Precommit\x12\x16\n" +
	"\x06aggsig\x18\x01 \x01(\fR\x06aggsig\x12\x14\n" +
	"\x05aggpk\x18\x02 \x01(\fR\x05aggpk\"9\n" +
	"\x11HS_Precommit_Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\rR\x04vote\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"9\n" +
	"\tHS_Commit\x12\x16\n" +
	"\x06aggsig\x18\x01 \x01(\fR\x06aggsig\x12\x14\n" +
	"\x05aggpk\x18\x02 \x01(\fR\x05aggpk\"\x1f\n" +
	"\vRBC_Propose\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"\x1c\n" +
	"\bRBC_Echo\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"+\n" +
	"\tRBC_Ready\x12\f\n" +
	"\x01h\x18\x01 \x01(\fR\x01h\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sigB\vZ\t/protobufb\x06proto3"

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData []byte
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP([]byte(file_Message_proto_rawDesc))
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Message_proto_goTypes = []any{
	(*Message)(nil),           // 0: Message
	(*HS_New_View)(nil),       // 1: HS_New_View
	(*HS_Prepare)(nil),        // 2: HS_Prepare
	(*HS_Prepare_Vote)(nil),   // 3: HS_Prepare_Vote
	(*HS_Precommit)(nil),      // 4: HS_Precommit
	(*HS_Precommit_Vote)(nil), // 5: HS_Precommit_Vote
	(*HS_Commit)(nil),         // 6: HS_Commit
	(*RBC_Propose)(nil),       // 7: RBC_Propose
	(*RBC_Echo)(nil),          // 8: RBC_Echo
	(*RBC_Ready)(nil),         // 9: RBC_Ready
}
var file_Message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: []byte(file_Message_proto_rawDesc),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
