// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.0
// source: Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Sender        uint32                 `protobuf:"varint,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_Message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// HotStuff (2-phase) messages
type HS_New_View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	None          []byte                 `protobuf:"bytes,1,opt,name=none,proto3" json:"none,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_New_View) Reset() {
	*x = HS_New_View{}
	mi := &file_Message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_New_View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_New_View) ProtoMessage() {}

func (x *HS_New_View) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_New_View.ProtoReflect.Descriptor instead.
func (*HS_New_View) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *HS_New_View) GetNone() []byte {
	if x != nil {
		return x.None
	}
	return nil
}

type HS_Prepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Prepare) Reset() {
	*x = HS_Prepare{}
	mi := &file_Message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Prepare) ProtoMessage() {}

func (x *HS_Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Prepare.ProtoReflect.Descriptor instead.
func (*HS_Prepare) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *HS_Prepare) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type HS_Prepare_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          uint32                 `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Prepare_Vote) Reset() {
	*x = HS_Prepare_Vote{}
	mi := &file_Message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Prepare_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Prepare_Vote) ProtoMessage() {}

func (x *HS_Prepare_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Prepare_Vote.ProtoReflect.Descriptor instead.
func (*HS_Prepare_Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *HS_Prepare_Vote) GetVote() uint32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *HS_Prepare_Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type HS_Precommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggsig        []byte                 `protobuf:"bytes,1,opt,name=aggsig,proto3" json:"aggsig,omitempty"`
	Aggpk         []byte                 `protobuf:"bytes,2,opt,name=aggpk,proto3" json:"aggpk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Precommit) Reset() {
	*x = HS_Precommit{}
	mi := &file_Message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Precommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Precommit) ProtoMessage() {}

func (x *HS_Precommit) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Precommit.ProtoReflect.Descriptor instead.
func (*HS_Precommit) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

func (x *HS_Precommit) GetAggsig() []byte {
	if x != nil {
		return x.Aggsig
	}
	return nil
}

func (x *HS_Precommit) GetAggpk() []byte {
	if x != nil {
		return x.Aggpk
	}
	return nil
}

type HS_Precommit_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          uint32                 `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Precommit_Vote) Reset() {
	*x = HS_Precommit_Vote{}
	mi := &file_Message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Precommit_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Precommit_Vote) ProtoMessage() {}

func (x *HS_Precommit_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Precommit_Vote.ProtoReflect.Descriptor instead.
func (*HS_Precommit_Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *HS_Precommit_Vote) GetVote() uint32 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *HS_Precommit_Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type HS_Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aggsig        []byte                 `protobuf:"bytes,1,opt,name=aggsig,proto3" json:"aggsig,omitempty"`
	Aggpk         []byte                 `protobuf:"bytes,2,opt,name=aggpk,proto3" json:"aggpk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HS_Commit) Reset() {
	*x = HS_Commit{}
	mi := &file_Message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HS_Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HS_Commit) ProtoMessage() {}

func (x *HS_Commit) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HS_Commit.ProtoReflect.Descriptor instead.
func (*HS_Commit) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{6}
}

func (x *HS_Commit) GetAggsig() []byte {
	if x != nil {
		return x.Aggsig
	}
	return nil
}

func (x *HS_Commit) GetAggpk() []byte {
	if x != nil {
		return x.Aggpk
	}
	return nil
}

// RBC messages
type RBC_Propose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Propose) Reset() {
	*x = RBC_Propose{}
	mi := &file_Message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Propose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Propose) ProtoMessage() {}

func (x *RBC_Propose) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Propose.ProtoReflect.Descriptor instead.
func (*RBC_Propose) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{7}
}

func (x *RBC_Propose) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type RBC_Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           []string               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Echo) Reset() {
	*x = RBC_Echo{}
	mi := &file_Message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Echo) ProtoMessage() {}

func (x *RBC_Echo) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Echo.ProtoReflect.Descriptor instead.
func (*RBC_Echo) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{8}
}

func (x *RBC_Echo) GetTxs() []string {
	if x != nil {
		return x.Txs
	}
	return nil
}

type RBC_Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	H             []byte                 `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Ready) Reset() {
	*x = RBC_Ready{}
	mi := &file_Message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Ready) ProtoMessage() {}

func (x *RBC_Ready) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Ready.ProtoReflect.Descriptor instead.
func (*RBC_Ready) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{9}
}

func (x *RBC_Ready) GetH() []byte {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *RBC_Ready) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

// Cross-shard: worker-shard nodes notify shard-0 about (2f+1) delivered RBC instances in an epoch.
// Bitmap length = ceil(N/8). Bit i corresponds to proposer SID i within that worker shard.
type RBC_Bitmap struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Shard  uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Epoch  uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Bitmap []byte                 `protobuf:"bytes,3,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	// Hashes for the 2f+1 RBC instances indicated by this bitmap.
	// Length = 2f+1, ordered by increasing RBC SID among the set bits.
	RbcHash       [][]byte `protobuf:"bytes,5,rep,name=rbc_hash,json=rbcHash,proto3" json:"rbc_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RBC_Bitmap) Reset() {
	*x = RBC_Bitmap{}
	mi := &file_Message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RBC_Bitmap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBC_Bitmap) ProtoMessage() {}

func (x *RBC_Bitmap) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBC_Bitmap.ProtoReflect.Descriptor instead.
func (*RBC_Bitmap) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{10}
}

func (x *RBC_Bitmap) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *RBC_Bitmap) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RBC_Bitmap) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

func (x *RBC_Bitmap) GetRbcHash() [][]byte {
	if x != nil {
		return x.RbcHash
	}
	return nil
}

// Cross-shard: shard-0 nodes send MVBA decided value back to the worker shard.
type MVBA_Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MVBA_Result) Reset() {
	*x = MVBA_Result{}
	mi := &file_Message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MVBA_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MVBA_Result) ProtoMessage() {}

func (x *MVBA_Result) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MVBA_Result.ProtoReflect.Descriptor instead.
func (*MVBA_Result) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{11}
}

func (x *MVBA_Result) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *MVBA_Result) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MVBA_Result) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// Provable Broadcast (PB) messages
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Validation    []byte                 `protobuf:"bytes,2,opt,name=validation,proto3" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_Message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{12}
}

func (x *Value) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetValidation() []byte {
	if x != nil {
		return x.Validation
	}
	return nil
}

type Echo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigshare      []byte                 `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Echo) Reset() {
	*x = Echo{}
	mi := &file_Message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{13}
}

func (x *Echo) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

// MVBA messages
type Lock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_Message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{14}
}

func (x *Lock) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Lock) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Finish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finish) Reset() {
	*x = Finish{}
	mi := &file_Message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finish) ProtoMessage() {}

func (x *Finish) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finish.ProtoReflect.Descriptor instead.
func (*Finish) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{15}
}

func (x *Finish) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Finish) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinShare     []byte                 `protobuf:"bytes,1,opt,name=coinShare,proto3" json:"coinShare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_Message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{16}
}

func (x *Done) GetCoinShare() []byte {
	if x != nil {
		return x.CoinShare
	}
	return nil
}

type Halt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Halt) Reset() {
	*x = Halt{}
	mi := &file_Message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Halt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Halt) ProtoMessage() {}

func (x *Halt) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Halt.ProtoReflect.Descriptor instead.
func (*Halt) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{17}
}

func (x *Halt) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Halt) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type PreVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          bool                   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreVote) Reset() {
	*x = PreVote{}
	mi := &file_Message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreVote) ProtoMessage() {}

func (x *PreVote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreVote.ProtoReflect.Descriptor instead.
func (*PreVote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{18}
}

func (x *PreVote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *PreVote) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PreVote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          bool                   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	Sigshare      []byte                 `protobuf:"bytes,4,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_Message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{19}
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *Vote) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Vote) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

// (Optional) MVBA default validation payloads (kept for compatibility).
type BLockSetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           []uint32               `protobuf:"varint,1,rep,packed,name=pid,proto3" json:"pid,omitempty"`
	Hash          [][]byte               `protobuf:"bytes,2,rep,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLockSetValue) Reset() {
	*x = BLockSetValue{}
	mi := &file_Message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLockSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLockSetValue) ProtoMessage() {}

func (x *BLockSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLockSetValue.ProtoReflect.Descriptor instead.
func (*BLockSetValue) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{20}
}

func (x *BLockSetValue) GetPid() []uint32 {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *BLockSetValue) GetHash() [][]byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BLockSetValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           [][]byte               `protobuf:"bytes,1,rep,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLockSetValidation) Reset() {
	*x = BLockSetValidation{}
	mi := &file_Message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLockSetValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLockSetValidation) ProtoMessage() {}

func (x *BLockSetValidation) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLockSetValidation.ProtoReflect.Descriptor instead.
func (*BLockSetValidation) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{21}
}

func (x *BLockSetValidation) GetSig() [][]byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_Message_proto protoreflect.FileDescriptor

const file_Message_proto_rawDesc = "" +
	"\n" +
	"\rMessage.proto\x12\bprotobuf\"Y\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\rR\x06sender\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"!\n" +
	"\vHS_New_View\x12\x12\n" +
	"\x04none\x18\x01 \x01(\fR\x04none\"\x1e\n" +
	"\n" +
	"HS_Prepare\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"7\n" +
	"\x0fHS_Prepare_Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\rR\x04vote\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"<\n" +
	"\fHS_Precommit\x12\x16\n" +
	"\x06aggsig\x18\x01 \x01(\fR\x06aggsig\x12\x14\n" +
	"\x05aggpk\x18\x02 \x01(\fR\x05aggpk\"9\n" +
	"\x11HS_Precommit_Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\rR\x04vote\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"9\n" +
	"\tHS_Commit\x12\x16\n" +
	"\x06aggsig\x18\x01 \x01(\fR\x06aggsig\x12\x14\n" +
	"\x05aggpk\x18\x02 \x01(\fR\x05aggpk\"\x1f\n" +
	"\vRBC_Propose\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"\x1c\n" +
	"\bRBC_Echo\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\tR\x03txs\"+\n" +
	"\tRBC_Ready\x12\f\n" +
	"\x01h\x18\x01 \x01(\fR\x01h\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"z\n" +
	"\n" +
	"RBC_Bitmap\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12\x16\n" +
	"\x06bitmap\x18\x03 \x01(\fR\x06bitmap\x12\x19\n" +
	"\brbc_hash\x18\x05 \x03(\fR\arbcHashJ\x04\b\x04\x10\x05R\arbc_sid\"Q\n" +
	"\vMVBA_Result\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\"=\n" +
	"\x05Value\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1e\n" +
	"\n" +
	"validation\x18\x02 \x01(\fR\n" +
	"validation\"\"\n" +
	"\x04Echo\x12\x1a\n" +
	"\bsigshare\x18\x01 \x01(\fR\bsigshare\".\n" +
	"\x04Lock\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"0\n" +
	"\x06Finish\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"$\n" +
	"\x04Done\x12\x1c\n" +
	"\tcoinShare\x18\x01 \x01(\fR\tcoinShare\".\n" +
	"\x04Halt\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"E\n" +
	"\aPreVote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\bR\x04vote\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\"^\n" +
	"\x04Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\bR\x04vote\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\x12\x1a\n" +
	"\bsigshare\x18\x04 \x01(\fR\bsigshare\"5\n" +
	"\rBLockSetValue\x12\x10\n" +
	"\x03pid\x18\x01 \x03(\rR\x03pid\x12\x12\n" +
	"\x04hash\x18\x02 \x03(\fR\x04hash\"&\n" +
	"\x12BLockSetValidation\x12\x10\n" +
	"\x03sig\x18\x01 \x03(\fR\x03sigB\vZ\t/protobufb\x06proto3"

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData []byte
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP([]byte(file_Message_proto_rawDesc))
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_Message_proto_goTypes = []any{
	(*Message)(nil),            // 0: protobuf.Message
	(*HS_New_View)(nil),        // 1: protobuf.HS_New_View
	(*HS_Prepare)(nil),         // 2: protobuf.HS_Prepare
	(*HS_Prepare_Vote)(nil),    // 3: protobuf.HS_Prepare_Vote
	(*HS_Precommit)(nil),       // 4: protobuf.HS_Precommit
	(*HS_Precommit_Vote)(nil),  // 5: protobuf.HS_Precommit_Vote
	(*HS_Commit)(nil),          // 6: protobuf.HS_Commit
	(*RBC_Propose)(nil),        // 7: protobuf.RBC_Propose
	(*RBC_Echo)(nil),           // 8: protobuf.RBC_Echo
	(*RBC_Ready)(nil),          // 9: protobuf.RBC_Ready
	(*RBC_Bitmap)(nil),         // 10: protobuf.RBC_Bitmap
	(*MVBA_Result)(nil),        // 11: protobuf.MVBA_Result
	(*Value)(nil),              // 12: protobuf.Value
	(*Echo)(nil),               // 13: protobuf.Echo
	(*Lock)(nil),               // 14: protobuf.Lock
	(*Finish)(nil),             // 15: protobuf.Finish
	(*Done)(nil),               // 16: protobuf.Done
	(*Halt)(nil),               // 17: protobuf.Halt
	(*PreVote)(nil),            // 18: protobuf.PreVote
	(*Vote)(nil),               // 19: protobuf.Vote
	(*BLockSetValue)(nil),      // 20: protobuf.BLockSetValue
	(*BLockSetValidation)(nil), // 21: protobuf.BLockSetValidation
}
var file_Message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: []byte(file_Message_proto_rawDesc),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
