N_M: 4
N_W: 4
F_M: 1
F_W: 1
m: 3
IPList:
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
PID: 0
SID: 0
Snum: 0
PortList:
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
Prepare: 5
Statistic: ./statistics
WaitEpoch: 12
WaitBuf: 40
MessageBuffer: 4096
TrackTraffic: true
Txnum: 10
Crate: 0.1
TestEpochs: 5
