N: 4
F: 1
m: 3
IPList:
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
PID: 0
SID: 1
Snum: 2
PortList:
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
PrepareTime: 50
Statistic: ./statistics
WaitTime: 120
Txnum: 10
Crate: 0.1
TestEpochs: 5
