N: 4
F: 1
m: 3
IPList:
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
PID: 0
SID: 1
Snum: 2
PortList:
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
- xxx
Prepare: 5
Statistic: ./statistics
WaitEpoch: 12
WaitBuf: 40
MessageBuffer: 4096
TrackTraffic: true
Txnum: 10
Crate: 0.1
TestEpochs: 5
