// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package chamaelrpc

import (
	"context"
	"fmt"
	"github.com/cloudwego/kitex/pkg/streaming"
)

type PushRequest struct {
	Sender  int32  `thrift:"sender,1,required" frugal:"1,required,i32" json:"sender"`
	Payload []byte `thrift:"payload,2,required" frugal:"2,required,binary" json:"payload"`
}

func NewPushRequest() *PushRequest {
	return &PushRequest{}
}

func (p *PushRequest) InitDefault() {
}

func (p *PushRequest) GetSender() (v int32) {
	return p.Sender
}

func (p *PushRequest) GetPayload() (v []byte) {
	return p.Payload
}
func (p *PushRequest) SetSender(val int32) {
	p.Sender = val
}
func (p *PushRequest) SetPayload(val []byte) {
	p.Payload = val
}

func (p *PushRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushRequest(%+v)", *p)
}

var fieldIDToName_PushRequest = map[int16]string{
	1: "sender",
	2: "payload",
}

type PushResponse struct {
}

func NewPushResponse() *PushResponse {
	return &PushResponse{}
}

func (p *PushResponse) InitDefault() {
}

func (p *PushResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushResponse(%+v)", *p)
}

var fieldIDToName_PushResponse = map[int16]string{}

type MessageService interface {
	Push(ctx context.Context, stream MessageService_PushServer) (err error)
}

type MessageServicePushArgs struct {
	Request *PushRequest `thrift:"request,1" frugal:"1,default,PushRequest" json:"request"`
}

func NewMessageServicePushArgs() *MessageServicePushArgs {
	return &MessageServicePushArgs{}
}

func (p *MessageServicePushArgs) InitDefault() {
}

var MessageServicePushArgs_Request_DEFAULT *PushRequest

func (p *MessageServicePushArgs) GetRequest() (v *PushRequest) {
	if !p.IsSetRequest() {
		return MessageServicePushArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *MessageServicePushArgs) SetRequest(val *PushRequest) {
	p.Request = val
}

func (p *MessageServicePushArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *MessageServicePushArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageServicePushArgs(%+v)", *p)
}

var fieldIDToName_MessageServicePushArgs = map[int16]string{
	1: "request",
}

type MessageServicePushResult struct {
	Success *PushResponse `thrift:"success,0,optional" frugal:"0,optional,PushResponse" json:"success,omitempty"`
}

func NewMessageServicePushResult() *MessageServicePushResult {
	return &MessageServicePushResult{}
}

func (p *MessageServicePushResult) InitDefault() {
}

var MessageServicePushResult_Success_DEFAULT *PushResponse

func (p *MessageServicePushResult) GetSuccess() (v *PushResponse) {
	if !p.IsSetSuccess() {
		return MessageServicePushResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MessageServicePushResult) SetSuccess(x interface{}) {
	p.Success = x.(*PushResponse)
}

func (p *MessageServicePushResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MessageServicePushResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageServicePushResult(%+v)", *p)
}

var fieldIDToName_MessageServicePushResult = map[int16]string{
	0: "success",
}

type MessageService_PushServer streaming.BidiStreamingServer[PushRequest, PushResponse]
