// Code generated by Kitex v0.16.2. DO NOT EDIT.

package messageservice

import (
	chamaelrpc "Chamael/pkg/kitex_gen/chamaelrpc"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Push": kitex.NewMethodInfo(
		pushHandler,
		newMessageServicePushArgs,
		newMessageServicePushResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingBidirectional),
	),
}

var (
	messageServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*chamaelrpc.MessageService)(nil)
	extra := map[string]interface{}{
		"PackageName": "chamaelrpc",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func pushHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, err := streaming.GetServerStreamFromArg(arg)
	if err != nil {
		return err
	}
	stream := streaming.NewBidiStreamingServer[chamaelrpc.PushRequest, chamaelrpc.PushResponse](st)
	return handler.(chamaelrpc.MessageService).Push(ctx, stream)
}

func newMessageServicePushArgs() interface{} {
	return chamaelrpc.NewMessageServicePushArgs()
}

func newMessageServicePushResult() interface{} {
	return chamaelrpc.NewMessageServicePushResult()
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) Push(ctx context.Context) (MessageService_PushClient, error) {
	st, err := p.sc.StreamX(ctx, "Push")
	if err != nil {
		return nil, err
	}
	stream := streaming.NewBidiStreamingClient[chamaelrpc.PushRequest, chamaelrpc.PushResponse](st)
	return stream, nil
}
